### ISSUE TITLE
How can I remove multiple file when using a polymorphic attachment model for file storage?

### ISSUE THREAD

**Issue by vnt** [josegonzalez/cakephp-upload#285] opened 2015-02-05 07:17 UTC
Hello,
I need an example for
Remove multiple file when using  a polymorphic attachment model for file storage:
http://cakephp-upload.readthedocs.org/en/latest/polymorphic.html
Can you help me?

Thank a lot.
D.

**Comment by davidyell** [comment] 2015-02-18 08:38
Duplicate of #267

**Closed by davidyell** 2015-02-18 08:38 UTC
