### ISSUE TITLE
thumbnail generation and file upload sometimes not working

### ISSUE THREAD

**Issue by q0re** [josegonzalez/cakephp-upload#290] opened 2015-03-07 15:57 UTC
I am able to upload files correctly via the form (select image from local source). The thumbnails were generated perfectly.

But if i use it without a form to pick up a file from a remote url, it does not work sometimes.

For example:

		$image_url = 'https://images.curved.de/article_detail/2014/03/macbookair.jpg';
		$this->Attachment->set(array('attachment' => $image_url));
		$this->Attachment->set(array('model' => 'Post'));
		$this->Attachment->save();

It saves only the original image without generating the thumbnails. If i use this image instead, all works fine: http://pmeyhoefer.de/blog/wp-content/uploads/2013/12/macbook_air.jpg

Another problem with this image example:
http://vignette2.wikia.nocookie.net/ipod/images/4/42/IWeb_macbook.png/revision/latest?cb=20110903153651
With this example, the base file name is "latest" without extension. So i cannot display this image. This is because $fileName = basename($socket->request['uri']['path']); fail in _grab() method. The thumbnailgeneration here is working.

i assume that i have configurated the plugin correctly. I tested it with php and imagick thumbnail generation, both methods are not working as i expect.

Whats the problem?

**Comment by davidyell** [comment] 2015-03-09 08:40
What is your expectation?

**Comment by q0re** [comment] 2015-03-09 09:18
My expectation is, that the thumbnails were generated. The thumbnail generation generally works fine, but not in some cases as explained above. The second problem is that the filename of the original image is not correct if the url is something like that http://vignette2.wikia.nocookie.net/ipod/images/4/42/IWeb_macbook.png/revision/latest?cb=20110903153651 In this example the filename is "latest" without extension (the thumbnails were generated correctly with extensions)

**Comment by q0re** [comment] 2015-03-09 13:47
I found the bug/problem.

In _grab() Method the 'type' of the requested source is set with $headers['Content-Type']. 
_createThumbnails checks if the type is in imageMimeTypes or _mediaMimetypes array. If both returns false, the thumbnails were not created.

The problem is the content-type of this link is text (i have no idea why)
https://images.curved.de/article_detail/2014/03/macbookair.jpg

Generally, is it a good idea to read the type from headers?

**Comment by davidyell** [comment] 2015-03-09 14:05
Sounds to me like the problem is with the image, not with the plugin.

**Comment by q0re** [comment] 2015-03-09 14:08
Oh i checked it again. The content-type of the image is 'image/jpg' (not text). And 'image/jpg' is not listed in _imageMimetypes  array (instead of ''image/jpeg''). So the problem is , 'image/jpg' is missing in the list of supported mime types.

**Comment by davidyell** [comment] 2015-03-09 15:07
Great, please can you send a PR to correct that, and we'll get it merged.

**Comment by q0re** [comment] 2015-03-09 17:51
Yes of course you are right, i am just wondering why this image has a wrong mime-type. Its not my image, i just found it via google. So its just a dummy.

**Comment by q0re** [comment] 2015-03-10 06:10
Now i have created a validation rule to check if its a valid mime type or not. This prevent that faulty images were uploaded without generating thumbnails. But i am just wondering why the original image is saved but the thumbnails not.

**Closed** 2015-03-10 06:11 UTC

**Comment by davidyell** [comment] 2015-03-10 14:40
Good idea :+1:
