### ISSUE TITLE
photo_dir returning 5%c in html->image (5%c = Windows backslash)

### ISSUE THREAD

**Issue by jon-h86** [josegonzalez/cakephp-upload#365] opened 2016-02-23 14:11 UTC
When I try to display the images using 

<?php echo $this->Html->image('/' . $user->photo_dir . $user->photo, ['alt' => 'CakePHP','escape' => false]); ?>

I get 5%c instead of backslashes in the directory.

webroot%5Cfiles%5CUsers%5Cphoto%5CButton-Upload-icon.png

How can i force it to put forward slashes into the directory to avoid this problem? 
How do people normally display images they uploaded with this plug in?

**Comment by josegonzalez** [comment] 2016-02-23 16:39
Probably a bug [here](https://github.com/josegonzalez/cakephp-upload/blob/master/src/File/Path/Basepath/DefaultTrait.php#L37).  You can avoid this by not using `{DS}`, or by doing a string replace to set the path correctly.

PRs welcome :)

**Comment by josegonzalez** [comment] 2016-02-23 16:40
Duplicate of #349.

**Closed by josegonzalez** 2016-02-23 16:40 UTC
Labels: 3.x, bug
